[server]
database_url = "postgres://user:pasword@localhost:5432/dbtest?sslmode=disable"
host = "127.0.0.1"
port = "8282"

[log]
level = "info"

[api]
api_key = "0000-0000-0000-0000-0000"
api_username = "MyUser"
api_password = "MyPassword"
api_server= "127.0.0.1"

[jwt]
jwt_secret= "MySecretPassword123"
jwt_secs= 3600 