[server]
database_url = "postgres://user:pasword@localhost:5432/dbtest?sslmode=disable"
host = "127.0.0.1"
port = "8282"

[log]
level = "info"

[openapi]
swagger = false

[api]
api_server= "https://"
api_user= ""
api_pass= ""

[jwt]
jwt_secret= ""
jwt_secs= 3600 
