[server]
database_url = "postgres://torogoz:T0r0g0z@207.244.235.5:5433/torogozpay?sslmode=disable"
host = "127.0.0.1"
port = "8282"

[log]
level = "debug"

[api]
api_key = "3ABC-9099-825A-7113-0E33"
api_username = "TorogozPay"
api_password = "CheritoCafe741"
api_server= "127.0.0.1"

[jwt]
jwt_secret= "MySecretPassword123"
jwt_secs= 3600 